// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/ffprobev1/ffprobe.proto

package ffprobev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ffprobev1_ffprobe_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type AnalyzeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FilePath        string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Container       string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	OverallBitrate  float64                `protobuf:"fixed64,5,opt,name=overall_bitrate,json=overallBitrate,proto3" json:"overall_bitrate,omitempty"`
	Video           *VideoStream           `protobuf:"bytes,6,opt,name=video,proto3" json:"video,omitempty"`
	Audio           []*AudioStream         `protobuf:"bytes,7,rep,name=audio,proto3" json:"audio,omitempty"`
	Subtitles       []*SubtitleStream      `protobuf:"bytes,8,rep,name=subtitles,proto3" json:"subtitles,omitempty"`
	Quality         *MediaQuality          `protobuf:"bytes,9,opt,name=quality,proto3" json:"quality,omitempty"`
	Error           string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	Chapters        []*Chapter             `protobuf:"bytes,11,rep,name=chapters,proto3" json:"chapters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ffprobev1_ffprobe_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *AnalyzeResponse) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *AnalyzeResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *AnalyzeResponse) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *AnalyzeResponse) GetOverallBitrate() float64 {
	if x != nil {
		return x.OverallBitrate
	}
	return 0
}

func (x *AnalyzeResponse) GetVideo() *VideoStream {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *AnalyzeResponse) GetAudio() []*AudioStream {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *AnalyzeResponse) GetSubtitles() []*SubtitleStream {
	if x != nil {
		return x.Subtitles
	}
	return nil
}

func (x *AnalyzeResponse) GetQuality() *MediaQuality {
	if x != nil {
		return x.Quality
	}
	return nil
}

func (x *AnalyzeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AnalyzeResponse) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type Chapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartSeconds  float64                `protobuf:"fixed64,3,opt,name=start_seconds,json=startSeconds,proto3" json:"start_seconds,omitempty"`
	EndSeconds    float64                `protobuf:"fixed64,4,opt,name=end_seconds,json=endSeconds,proto3" json:"end_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_proto_ffprobev1_ffprobe_proto_rawDescGZIP(), []int{2}
}

func (x *Chapter) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Chapter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chapter) GetStartSeconds() float64 {
	if x != nil {
		return x.StartSeconds
	}
	return 0
}

func (x *Chapter) GetEndSeconds() float64 {
	if x != nil {
		return x.EndSeconds
	}
	return 0
}

type VideoStream struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Index           int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Codec           string                 `protobuf:"bytes,2,opt,name=codec,proto3" json:"codec,omitempty"`
	CodecLong       string                 `protobuf:"bytes,3,opt,name=codec_long,json=codecLong,proto3" json:"codec_long,omitempty"`
	Width           int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height          int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	ResolutionLabel string                 `protobuf:"bytes,6,opt,name=resolution_label,json=resolutionLabel,proto3" json:"resolution_label,omitempty"`
	FrameRate       float64                `protobuf:"fixed64,7,opt,name=frame_rate,json=frameRate,proto3" json:"frame_rate,omitempty"`
	Bitrate         float64                `protobuf:"fixed64,8,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	PixelFormat     string                 `protobuf:"bytes,9,opt,name=pixel_format,json=pixelFormat,proto3" json:"pixel_format,omitempty"`
	ColorPrimaries  string                 `protobuf:"bytes,10,opt,name=color_primaries,json=colorPrimaries,proto3" json:"color_primaries,omitempty"`
	ColorTransfer   string                 `protobuf:"bytes,11,opt,name=color_transfer,json=colorTransfer,proto3" json:"color_transfer,omitempty"`
	ColorSpace      string                 `protobuf:"bytes,12,opt,name=color_space,json=colorSpace,proto3" json:"color_space,omitempty"`
	Hdr             bool                   `protobuf:"varint,13,opt,name=hdr,proto3" json:"hdr,omitempty"`
	HdrType         string                 `protobuf:"bytes,14,opt,name=hdr_type,json=hdrType,proto3" json:"hdr_type,omitempty"` // "HDR10", "HDR10+", "Dolby Vision", "HLG", ""
	AspectRatio     string                 `protobuf:"bytes,15,opt,name=aspect_ratio,json=aspectRatio,proto3" json:"aspect_ratio,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VideoStream) Reset() {
	*x = VideoStream{}
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStream) ProtoMessage() {}

func (x *VideoStream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStream.ProtoReflect.Descriptor instead.
func (*VideoStream) Descriptor() ([]byte, []int) {
	return file_proto_ffprobev1_ffprobe_proto_rawDescGZIP(), []int{3}
}

func (x *VideoStream) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *VideoStream) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *VideoStream) GetCodecLong() string {
	if x != nil {
		return x.CodecLong
	}
	return ""
}

func (x *VideoStream) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoStream) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoStream) GetResolutionLabel() string {
	if x != nil {
		return x.ResolutionLabel
	}
	return ""
}

func (x *VideoStream) GetFrameRate() float64 {
	if x != nil {
		return x.FrameRate
	}
	return 0
}

func (x *VideoStream) GetBitrate() float64 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *VideoStream) GetPixelFormat() string {
	if x != nil {
		return x.PixelFormat
	}
	return ""
}

func (x *VideoStream) GetColorPrimaries() string {
	if x != nil {
		return x.ColorPrimaries
	}
	return ""
}

func (x *VideoStream) GetColorTransfer() string {
	if x != nil {
		return x.ColorTransfer
	}
	return ""
}

func (x *VideoStream) GetColorSpace() string {
	if x != nil {
		return x.ColorSpace
	}
	return ""
}

func (x *VideoStream) GetHdr() bool {
	if x != nil {
		return x.Hdr
	}
	return false
}

func (x *VideoStream) GetHdrType() string {
	if x != nil {
		return x.HdrType
	}
	return ""
}

func (x *VideoStream) GetAspectRatio() string {
	if x != nil {
		return x.AspectRatio
	}
	return ""
}

type AudioStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Codec         string                 `protobuf:"bytes,2,opt,name=codec,proto3" json:"codec,omitempty"`
	CodecLong     string                 `protobuf:"bytes,3,opt,name=codec_long,json=codecLong,proto3" json:"codec_long,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Channels      int32                  `protobuf:"varint,5,opt,name=channels,proto3" json:"channels,omitempty"`
	ChannelLayout string                 `protobuf:"bytes,6,opt,name=channel_layout,json=channelLayout,proto3" json:"channel_layout,omitempty"`
	Bitrate       float64                `protobuf:"fixed64,7,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Profile       string                 `protobuf:"bytes,8,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioStream) Reset() {
	*x = AudioStream{}
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioStream) ProtoMessage() {}

func (x *AudioStream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioStream.ProtoReflect.Descriptor instead.
func (*AudioStream) Descriptor() ([]byte, []int) {
	return file_proto_ffprobev1_ffprobe_proto_rawDescGZIP(), []int{4}
}

func (x *AudioStream) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *AudioStream) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *AudioStream) GetCodecLong() string {
	if x != nil {
		return x.CodecLong
	}
	return ""
}

func (x *AudioStream) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AudioStream) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioStream) GetChannelLayout() string {
	if x != nil {
		return x.ChannelLayout
	}
	return ""
}

func (x *AudioStream) GetBitrate() float64 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *AudioStream) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type SubtitleStream struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Index           int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Codec           string                 `protobuf:"bytes,2,opt,name=codec,proto3" json:"codec,omitempty"`
	Language        string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Forced          bool                   `protobuf:"varint,4,opt,name=forced,proto3" json:"forced,omitempty"`
	HearingImpaired bool                   `protobuf:"varint,5,opt,name=hearing_impaired,json=hearingImpaired,proto3" json:"hearing_impaired,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubtitleStream) Reset() {
	*x = SubtitleStream{}
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtitleStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtitleStream) ProtoMessage() {}

func (x *SubtitleStream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtitleStream.ProtoReflect.Descriptor instead.
func (*SubtitleStream) Descriptor() ([]byte, []int) {
	return file_proto_ffprobev1_ffprobe_proto_rawDescGZIP(), []int{5}
}

func (x *SubtitleStream) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SubtitleStream) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *SubtitleStream) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SubtitleStream) GetForced() bool {
	if x != nil {
		return x.Forced
	}
	return false
}

func (x *SubtitleStream) GetHearingImpaired() bool {
	if x != nil {
		return x.HearingImpaired
	}
	return false
}

type MediaQuality struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"` // "2160p Remux", "1080p WEB-DL", etc.
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Resolution    string                 `protobuf:"bytes,3,opt,name=resolution,proto3" json:"resolution,omitempty"`                   // "2160p", "1080p", "720p", "SD"
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`                           // "Remux", "BluRay", "WEB-DL", "HDTV", etc.
	CodecGroup    string                 `protobuf:"bytes,5,opt,name=codec_group,json=codecGroup,proto3" json:"codec_group,omitempty"` // "h264", "hevc", "av1", "vp9"
	Hdr           bool                   `protobuf:"varint,6,opt,name=hdr,proto3" json:"hdr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaQuality) Reset() {
	*x = MediaQuality{}
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaQuality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaQuality) ProtoMessage() {}

func (x *MediaQuality) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaQuality.ProtoReflect.Descriptor instead.
func (*MediaQuality) Descriptor() ([]byte, []int) {
	return file_proto_ffprobev1_ffprobe_proto_rawDescGZIP(), []int{6}
}

func (x *MediaQuality) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MediaQuality) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MediaQuality) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *MediaQuality) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MediaQuality) GetCodecGroup() string {
	if x != nil {
		return x.CodecGroup
	}
	return ""
}

func (x *MediaQuality) GetHdr() bool {
	if x != nil {
		return x.Hdr
	}
	return false
}

type GetCachedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCachedRequest) Reset() {
	*x = GetCachedRequest{}
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCachedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCachedRequest) ProtoMessage() {}

func (x *GetCachedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCachedRequest.ProtoReflect.Descriptor instead.
func (*GetCachedRequest) Descriptor() ([]byte, []int) {
	return file_proto_ffprobev1_ffprobe_proto_rawDescGZIP(), []int{7}
}

func (x *GetCachedRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type GetCachedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *AnalyzeResponse       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCachedResponse) Reset() {
	*x = GetCachedResponse{}
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCachedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCachedResponse) ProtoMessage() {}

func (x *GetCachedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffprobev1_ffprobe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCachedResponse.ProtoReflect.Descriptor instead.
func (*GetCachedResponse) Descriptor() ([]byte, []int) {
	return file_proto_ffprobev1_ffprobe_proto_rawDescGZIP(), []int{8}
}

func (x *GetCachedResponse) GetResult() *AnalyzeResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetCachedResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_proto_ffprobev1_ffprobe_proto protoreflect.FileDescriptor

const file_proto_ffprobev1_ffprobe_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/ffprobev1/ffprobe.proto\x12\x12muxcore.ffprobe.v1\"-\n" +
	"\x0eAnalyzeRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"\xfa\x03\n" +
	"\x0fAnalyzeResponse\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x01R\x0fdurationSeconds\x12'\n" +
	"\x0foverall_bitrate\x18\x05 \x01(\x01R\x0eoverallBitrate\x125\n" +
	"\x05video\x18\x06 \x01(\v2\x1f.muxcore.ffprobe.v1.VideoStreamR\x05video\x125\n" +
	"\x05audio\x18\a \x03(\v2\x1f.muxcore.ffprobe.v1.AudioStreamR\x05audio\x12@\n" +
	"\tsubtitles\x18\b \x03(\v2\".muxcore.ffprobe.v1.SubtitleStreamR\tsubtitles\x12:\n" +
	"\aquality\x18\t \x01(\v2 .muxcore.ffprobe.v1.MediaQualityR\aquality\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x127\n" +
	"\bchapters\x18\v \x03(\v2\x1b.muxcore.ffprobe.v1.ChapterR\bchapters\"{\n" +
	"\aChapter\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rstart_seconds\x18\x03 \x01(\x01R\fstartSeconds\x12\x1f\n" +
	"\vend_seconds\x18\x04 \x01(\x01R\n" +
	"endSeconds\"\xce\x03\n" +
	"\vVideoStream\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x14\n" +
	"\x05codec\x18\x02 \x01(\tR\x05codec\x12\x1d\n" +
	"\n" +
	"codec_long\x18\x03 \x01(\tR\tcodecLong\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12)\n" +
	"\x10resolution_label\x18\x06 \x01(\tR\x0fresolutionLabel\x12\x1d\n" +
	"\n" +
	"frame_rate\x18\a \x01(\x01R\tframeRate\x12\x18\n" +
	"\abitrate\x18\b \x01(\x01R\abitrate\x12!\n" +
	"\fpixel_format\x18\t \x01(\tR\vpixelFormat\x12'\n" +
	"\x0fcolor_primaries\x18\n" +
	" \x01(\tR\x0ecolorPrimaries\x12%\n" +
	"\x0ecolor_transfer\x18\v \x01(\tR\rcolorTransfer\x12\x1f\n" +
	"\vcolor_space\x18\f \x01(\tR\n" +
	"colorSpace\x12\x10\n" +
	"\x03hdr\x18\r \x01(\bR\x03hdr\x12\x19\n" +
	"\bhdr_type\x18\x0e \x01(\tR\ahdrType\x12!\n" +
	"\faspect_ratio\x18\x0f \x01(\tR\vaspectRatio\"\xeb\x01\n" +
	"\vAudioStream\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x14\n" +
	"\x05codec\x18\x02 \x01(\tR\x05codec\x12\x1d\n" +
	"\n" +
	"codec_long\x18\x03 \x01(\tR\tcodecLong\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1a\n" +
	"\bchannels\x18\x05 \x01(\x05R\bchannels\x12%\n" +
	"\x0echannel_layout\x18\x06 \x01(\tR\rchannelLayout\x12\x18\n" +
	"\abitrate\x18\a \x01(\x01R\abitrate\x12\x18\n" +
	"\aprofile\x18\b \x01(\tR\aprofile\"\x9b\x01\n" +
	"\x0eSubtitleStream\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x14\n" +
	"\x05codec\x18\x02 \x01(\tR\x05codec\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x16\n" +
	"\x06forced\x18\x04 \x01(\bR\x06forced\x12)\n" +
	"\x10hearing_impaired\x18\x05 \x01(\bR\x0fhearingImpaired\"\xa5\x01\n" +
	"\fMediaQuality\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x1e\n" +
	"\n" +
	"resolution\x18\x03 \x01(\tR\n" +
	"resolution\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1f\n" +
	"\vcodec_group\x18\x05 \x01(\tR\n" +
	"codecGroup\x12\x10\n" +
	"\x03hdr\x18\x06 \x01(\bR\x03hdr\"/\n" +
	"\x10GetCachedRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"f\n" +
	"\x11GetCachedResponse\x12;\n" +
	"\x06result\x18\x01 \x01(\v2#.muxcore.ffprobe.v1.AnalyzeResponseR\x06result\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found2\xbf\x01\n" +
	"\x0fAnalysisService\x12R\n" +
	"\aAnalyze\x12\".muxcore.ffprobe.v1.AnalyzeRequest\x1a#.muxcore.ffprobe.v1.AnalyzeResponse\x12X\n" +
	"\tGetCached\x12$.muxcore.ffprobe.v1.GetCachedRequest\x1a%.muxcore.ffprobe.v1.GetCachedResponseBBZ@github.com/Muxcore-Media/media-ffprobe/proto/ffprobev1;ffprobev1b\x06proto3"

var (
	file_proto_ffprobev1_ffprobe_proto_rawDescOnce sync.Once
	file_proto_ffprobev1_ffprobe_proto_rawDescData []byte
)

func file_proto_ffprobev1_ffprobe_proto_rawDescGZIP() []byte {
	file_proto_ffprobev1_ffprobe_proto_rawDescOnce.Do(func() {
		file_proto_ffprobev1_ffprobe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ffprobev1_ffprobe_proto_rawDesc), len(file_proto_ffprobev1_ffprobe_proto_rawDesc)))
	})
	return file_proto_ffprobev1_ffprobe_proto_rawDescData
}

var file_proto_ffprobev1_ffprobe_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_ffprobev1_ffprobe_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),    // 0: muxcore.ffprobe.v1.AnalyzeRequest
	(*AnalyzeResponse)(nil),   // 1: muxcore.ffprobe.v1.AnalyzeResponse
	(*Chapter)(nil),           // 2: muxcore.ffprobe.v1.Chapter
	(*VideoStream)(nil),       // 3: muxcore.ffprobe.v1.VideoStream
	(*AudioStream)(nil),       // 4: muxcore.ffprobe.v1.AudioStream
	(*SubtitleStream)(nil),    // 5: muxcore.ffprobe.v1.SubtitleStream
	(*MediaQuality)(nil),      // 6: muxcore.ffprobe.v1.MediaQuality
	(*GetCachedRequest)(nil),  // 7: muxcore.ffprobe.v1.GetCachedRequest
	(*GetCachedResponse)(nil), // 8: muxcore.ffprobe.v1.GetCachedResponse
}
var file_proto_ffprobev1_ffprobe_proto_depIdxs = []int32{
	3, // 0: muxcore.ffprobe.v1.AnalyzeResponse.video:type_name -> muxcore.ffprobe.v1.VideoStream
	4, // 1: muxcore.ffprobe.v1.AnalyzeResponse.audio:type_name -> muxcore.ffprobe.v1.AudioStream
	5, // 2: muxcore.ffprobe.v1.AnalyzeResponse.subtitles:type_name -> muxcore.ffprobe.v1.SubtitleStream
	6, // 3: muxcore.ffprobe.v1.AnalyzeResponse.quality:type_name -> muxcore.ffprobe.v1.MediaQuality
	2, // 4: muxcore.ffprobe.v1.AnalyzeResponse.chapters:type_name -> muxcore.ffprobe.v1.Chapter
	1, // 5: muxcore.ffprobe.v1.GetCachedResponse.result:type_name -> muxcore.ffprobe.v1.AnalyzeResponse
	0, // 6: muxcore.ffprobe.v1.AnalysisService.Analyze:input_type -> muxcore.ffprobe.v1.AnalyzeRequest
	7, // 7: muxcore.ffprobe.v1.AnalysisService.GetCached:input_type -> muxcore.ffprobe.v1.GetCachedRequest
	1, // 8: muxcore.ffprobe.v1.AnalysisService.Analyze:output_type -> muxcore.ffprobe.v1.AnalyzeResponse
	8, // 9: muxcore.ffprobe.v1.AnalysisService.GetCached:output_type -> muxcore.ffprobe.v1.GetCachedResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_ffprobev1_ffprobe_proto_init() }
func file_proto_ffprobev1_ffprobe_proto_init() {
	if File_proto_ffprobev1_ffprobe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ffprobev1_ffprobe_proto_rawDesc), len(file_proto_ffprobev1_ffprobe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ffprobev1_ffprobe_proto_goTypes,
		DependencyIndexes: file_proto_ffprobev1_ffprobe_proto_depIdxs,
		MessageInfos:      file_proto_ffprobev1_ffprobe_proto_msgTypes,
	}.Build()
	File_proto_ffprobev1_ffprobe_proto = out.File
	file_proto_ffprobev1_ffprobe_proto_goTypes = nil
	file_proto_ffprobev1_ffprobe_proto_depIdxs = nil
}
